### ISSUE TITLE
Issues with Nokogiri 1.13.5 and 1.13.6

### ISSUE THREAD

**Issue by Adsidera** [jorgemanrubia/truncato#20]
After upgrading Nokogiri to version 1.13.5 (or 1.13.6), we get this:

```ruby
Truncato.truncate "<p>some text</p>", max_length: 4
"&lt;<p>...</p>"

Truncato.truncate "<p>some text</p>"
"&lt;<p>__truncato_root__&gt;</p><p>s...</p>"
```

Can you please advise?

**Comment by franzliedke** [comment]
In case this helps: The [Nokogiri changelog](https://github.com/sparklemotion/nokogiri/blob/main/CHANGELOG.md#1135--2022-05-04) lists this as a known breakage (part of a security fix):

>  * [CRuby] The libxml2 HTML parser in v2.9.14 recovers from some broken markup differently. Notably, the XML CDATA escape sequence `<![CDATA[` and incorrectly-opened comments will result in HTML text nodes starting with `&lt;!` instead of skipping the invalid tag. This behavior is a direct result of the [quadratic-behavior fix](https://gitlab.gnome.org/GNOME/libxml2/-/commit/798bdf1) noted above. The behavior of downstream sanitizers relying on this behavior will also change. Some tests describing the changed behavior are in [`test/html4/test_comments.rb`](https://github.com/sparklemotion/nokogiri/blob/3ed5bf2b5a367cb9dc6e329c5a1c512e1dd4565d/test/html4/test_comments.rb#L187-L204).

So apparently we're dealing with broken markup here? Is that intended? (I did not look into the Truncato code yet.)

**Comment by PierreMesure** [comment]
Good catch!

**Comment by mattyoho** [comment]
FWIW, in a Rails context, tossing this in an initializer will avoid the bug:

```ruby
silence_warnings do
  Truncato::ARTIFICIAL_ROOT_NAME = "truncato-artificial-root".freeze
end
```

That will override the gem-defined value, which is probably an invalid tag name due to the underscores: https://github.com/jorgemanrubia/truncato/blob/7b93028ce9988810d3f95d513b7bc60f0a8fe7bd/lib/truncato/truncato.rb#L9

PR opened here https://github.com/jorgemanrubia/truncato/pull/21.

**Comment by jorgemanrubia** [comment]
Fixed via https://github.com/jorgemanrubia/truncato/pull/21.
